config/routes.rb
Rails.application.routes.draw do
  resources :shop
  root 'shop#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :shop
end

app/models/shop.rb
class Shop < ApplicationRecord
  has_one :schedule
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/shop_controller.rb
class ShopController < ApplicationController
  def index
    @shops = Shop.all
  end

  def show
    @shop = Shop.find(params[:id])
  end


  private
  def shop_params
    params.require(:shop).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shop_helper.rb
module ShopHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StoresSchedule</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shop/index.html.erb
<h1>Shops</h1>

<div id="shops">
  <% @shops.each do |shop| %>
    <%= shop.name %>
    <p>
      <%= link_to "Shop's schedule", shop %>
    </p>
  <% end %>
</div>

app/views/shop/show.html.erb
<h1> <%= @shop.name %> </h1>

<h2> Schedule: </h2>

<% schedule = @shop.schedule %>

<% day = Date.today.strftime("%A") %>
<% days = { "Monday" => schedule.lundi, "Tuesday" => schedule.mardi, "Wednesday" => schedule.mercredi , "Thursday" => schedule.jeudi ,"Friday" => schedule.vendredi,"Saturday" => schedule.samedi,"Sunday" => schedule.dimanche}%>

<% found = false %>
<% days.each do |key, hour| %>
  <% if found == true %>
    <div><%= key %>: <%= hour %></div>
    <% days.delete(key) %> 
  <% elsif key == day %> 
    <div><b><%= key %>: <%= hour %> </b></div>
    <% days.delete(key) %> 
    <% found = true %> 
  <% end %>
<% end %>

<% days.each do |key, hour| %>
  <div><%= key %>: <%= hour %></div>
<% end %>

<br>
<%= link_to 'Shop index', shop_index_path %>